---
version: "3"

services:
  rhm_measure:
    privileged: true
    image: bproszkowiec/hm-deamon
    # build: ./hm-deamon
    container_name: hm-deamon
    restart: unless-stopped
    depends_on:
      - rhm_api
    env_file: .env
    environment:
      API_IP: rhm_api
    ports:
      - "${SRV_MEAS_PORT}:${SRV_MEAS_PORT}/udp"

  rhm_api:
    image: bproszkowiec/hm-api
    # build: ./hm-rest-api
    container_name: hm-api
    restart: unless-stopped
    depends_on:
      - mysql
    env_file: .env
    environment:
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
      DB_DATABASE: ${MARIADB_DATABASE}
      DB_HOST: mysql

  mysql:
    image: tobi312/rpi-mariadb:10.6-alpine
    container_name: hm-mariadb
    env_file: .env
    volumes:
      - database:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main
    container_name: hm-grafana
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  database: {}
  grafana-storage: {}
