CREATE DATABASE IF NOT EXISTS data_db;
USE data_db;

CREATE TABLE IF NOT EXISTS weather_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp_utc TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    temperature DECIMAL(3,1),
    humidity DECIMAL(3,1)
);
